# Generated by Django 2.2 on 2020-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, help_text='Name', max_length=80, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=80, null=True)),
                ('message', models.CharField(blank=True, help_text='Message', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
