# Generated by Django 2.2 on 2020-05-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
                ('center', models.CharField(blank=True, help_text='Name of the Certifying Center', max_length=80, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the certificate.', null=True)),
                ('date', models.DateField(blank=True, help_text='Date of obtainment', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email of the User', max_length=80, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, help_text='Phone no of the User', null=True)),
                ('url', models.URLField(blank=True, help_text='Portfolio Url', null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the User', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
                ('start', models.DateField(blank=True, help_text='give it a  start date.', max_length=100, null=True)),
                ('end', models.DateField(blank=True, help_text='give it a end date.', max_length=100, null=True)),
                ('course', models.CharField(blank=True, help_text='Name of the course.', max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, help_text='GPA/SCORE.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
                ('start', models.DateField(blank=True, help_text='give it a  start date.', max_length=100, null=True)),
                ('end', models.DateField(blank=True, help_text='give it a end date.', max_length=100, null=True)),
                ('position', models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='give it a description.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
                ('start', models.DateField(blank=True, help_text='give it a  start date.', max_length=100, null=True)),
                ('end', models.DateField(blank=True, help_text='give it a end date.', max_length=100, null=True)),
                ('position', models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='give it a description.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
                ('date', models.DateField(blank=True, help_text='give it a date.', max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text='Describe the role in the project.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='give it a description.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='give it a name.', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Full Name of the User', max_length=80, null=True)),
                ('age', models.DateField(blank=True, help_text='Age of the User', null=True)),
                ('position', models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True)),
                ('profile', models.TextField(blank=True, help_text='Profile/ description of the User', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('text', 'multitext', 'url')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='resume.UserResume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
