# Generated by Django 2.2 on 2020-06-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resume_number', models.PositiveIntegerField(blank=True, help_text='Resume number')),
                ('name', models.CharField(blank=True, help_text='Full Name of the User', max_length=80, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age of the User', null=True)),
                ('position', models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True)),
                ('profile', models.TextField(blank=True, help_text='Profile/ description of the User', null=True)),
                ('achievements', models.TextField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, max_length=100, null=True)),
                ('interests', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the User', max_length=80, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, help_text='Phone no of the User', null=True)),
                ('url', models.URLField(blank=True, help_text='Portfolio Url', null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the User', null=True)),
                ('education_institute', models.CharField(blank=True, help_text='Name of the Institute.', max_length=80, null=True)),
                ('education_start', models.DateField(blank=True, help_text='give it a  start date.', max_length=80, null=True)),
                ('education_end', models.DateField(blank=True, help_text='give it a end date.', max_length=80, null=True)),
                ('education_course', models.CharField(blank=True, help_text='Name of the course.', max_length=80, null=True)),
                ('education_score', models.IntegerField(blank=True, help_text='GPA/SCORE.', null=True)),
                ('intern_company', models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True)),
                ('intern_position', models.CharField(blank=True, help_text='Position of the User', max_length=80, null=True)),
                ('intern_start', models.DateField(blank=True, help_text='give it a  start date.', max_length=80, null=True)),
                ('intern_end', models.DateField(blank=True, help_text='give it a end date.', max_length=80, null=True)),
                ('intern_description', models.TextField(blank=True, help_text='give it a description.', max_length=80, null=True)),
                ('experience_company_1', models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True)),
                ('experience_position_1', models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True)),
                ('experience_start_1', models.DateField(blank=True, help_text='give it a  start date.', max_length=80, null=True)),
                ('experience_end_1', models.DateField(blank=True, help_text='give it a end date.', max_length=80, null=True)),
                ('experience_description_1', models.TextField(blank=True, help_text='give it a description.', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
