# Generated by Django 2.2 on 2020-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, help_text='UserId', max_length=80, null=True)),
                ('resume_number', models.PositiveIntegerField(blank=True, help_text='Resume number', null=True)),
                ('page2active', models.CharField(blank=True, max_length=10, null=True)),
                ('internActive', models.CharField(blank=True, max_length=10, null=True)),
                ('projectActive', models.CharField(blank=True, max_length=10, null=True)),
                ('certificateActive', models.CharField(blank=True, max_length=10, null=True)),
                ('recommendationActive', models.CharField(blank=True, max_length=10, null=True)),
                ('achievementNum', models.PositiveIntegerField(blank=True, null=True)),
                ('skillNum', models.PositiveIntegerField(blank=True, null=True)),
                ('interestNum', models.PositiveIntegerField(blank=True, null=True)),
                ('experienceNum', models.PositiveIntegerField(blank=True, null=True)),
                ('projectNum', models.PositiveIntegerField(blank=True, null=True)),
                ('certificateNum', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendationNum', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userresume',
            name='resume_image',
            field=models.ImageField(blank=True, default='user_resume_image/default.jpg', null=True, upload_to='user_resume_image'),
        ),
    ]
