# Generated by Django 2.2 on 2020-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='education_degree',
            field=models.CharField(blank=True, help_text='Name of the degree.', max_length=80, null=True),
        ),
    ]
