# Generated by Django 2.2 on 2020-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='experience_company_2',
            field=models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_description_2',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_end_2',
            field=models.DateField(blank=True, help_text='give it a end date.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_position_2',
            field=models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_start_2',
            field=models.DateField(blank=True, help_text='give it a  start date.', max_length=80, null=True),
        ),
    ]
