# Generated by Django 2.2 on 2020-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200605_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='certificate_name_1',
            field=models.CharField(blank=True, help_text='Name of the Certificate', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certificate_name_2',
            field=models.CharField(blank=True, help_text='Name of the Certificate', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certificate_name_3',
            field=models.CharField(blank=True, help_text='Name of the Certificate', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certificate_obtainment_date_1',
            field=models.DateField(blank=True, help_text='Date of obtainment', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certificate_obtainment_date_2',
            field=models.DateField(blank=True, help_text='Date of obtainment', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certificate_obtainment_date_3',
            field=models.DateField(blank=True, help_text='Date of obtainment', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certification_description_1',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certification_description_2',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certification_description_3',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certifying_center_1',
            field=models.CharField(blank=True, help_text='Name of the Cerifying Center', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certifying_center_2',
            field=models.CharField(blank=True, help_text='Name of the Cerifying Center', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='certifying_center_3',
            field=models.CharField(blank=True, help_text='Name of the Cerifying Center', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_company_3',
            field=models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_company_4',
            field=models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_description_3',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_description_4',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_end_3',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_end_4',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_position_3',
            field=models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_position_4',
            field=models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_start_3',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_start_4',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_end_1',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_end_2',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_end_3',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_name_1',
            field=models.CharField(blank=True, help_text='Name of the Project', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_name_2',
            field=models.CharField(blank=True, help_text='Name of the Project', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_name_3',
            field=models.CharField(blank=True, help_text='Name of the Project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_role_1',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_role_2',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_role_3',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_start_1',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_start_2',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='project_start_3',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendation_1',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendation_2',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendation_3',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendation_4',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendation_5',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='achievements',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education_end',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education_start',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_1',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_2',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_1',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_2',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='interests',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_end',
            field=models.DateField(blank=True, help_text='give it a end date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_start',
            field=models.DateField(blank=True, help_text='give it a  start date.', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
