# Generated by Django 2.2 on 2020-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_userresume_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_1',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_2',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_3',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_1',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_2',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_3',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_4',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_description',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_1',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_2',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_3',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_1',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_2',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_3',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_4',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_5',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
