# Generated by Django 2.2 on 2020-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200706_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the User', null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education_score',
            field=models.PositiveIntegerField(blank=True, help_text='GPA/SCORE.', null=True),
        ),
    ]
