# Generated by Django 2.2 on 2020-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200605_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='achievements',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certificate_obtainment_date_1',
            field=models.CharField(blank=True, help_text='Date of obtainment', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certificate_obtainment_date_2',
            field=models.CharField(blank=True, help_text='Date of obtainment', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certificate_obtainment_date_3',
            field=models.CharField(blank=True, help_text='Date of obtainment', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_1',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_2',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certification_description_3',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education_end',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='education_start',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_1',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_2',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_3',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_4',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_1',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_2',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_3',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_end_4',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_1',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_2',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_3',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_start_4',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='interests',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_description',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_end',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_start',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone no of the User', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_end_1',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_end_2',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_end_3',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_1',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_2',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_role_3',
            field=models.TextField(blank=True, help_text='Role in the Project', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_start_1',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_start_2',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_start_3',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='skills',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
