# Generated by Django 2.2 on 2020-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200707_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='education_score',
            field=models.FloatField(blank=True, help_text='GPA/SCORE.', null=True),
        ),
    ]
