# Generated by Django 2.2 on 2020-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200710_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='recommendation_1',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='recommendation_2',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='recommendation_3',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='recommendation_4',
        ),
        migrations.RemoveField(
            model_name='userresume',
            name='recommendation_5',
        ),
        migrations.AddField(
            model_name='userresume',
            name='recommendations',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
