# Generated by Django 2.2 on 2020-06-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200609_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='certification_description_1',
            new_name='certificate_description_1',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='certification_description_2',
            new_name='certificate_description_2',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='certification_description_3',
            new_name='certificate_description_3',
        ),
    ]
