# Generated by Django 2.2 on 2020-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200711_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='certificate_description_1',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certificate_description_2',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='certificate_description_3',
            field=models.TextField(blank=True, help_text='Describe your certification', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_1',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_2',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_3',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='experience_description_4',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='intern_description',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_description_1',
            field=models.TextField(blank=True, help_text='Decsribe Project', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_description_2',
            field=models.TextField(blank=True, help_text='Describe Project', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='project_description_3',
            field=models.TextField(blank=True, help_text='Describe Project', max_length=1000, null=True),
        ),
    ]
