# Generated by Django 2.2 on 2020-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200609_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_1',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_2',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_3',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_4',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='recommendation_5',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
