# Generated by Django 2.2 on 2020-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200609_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='url',
            field=models.CharField(blank=True, help_text='Portfolio Url', max_length=50, null=True),
        ),
    ]
