# Generated by Django 2.2 on 2020-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200717_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='experience_company_5',
            field=models.CharField(blank=True, help_text='Name of the Company', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_description_5',
            field=models.TextField(blank=True, help_text='give it a description.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_end_5',
            field=models.CharField(blank=True, help_text='give it a end date.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_position_5',
            field=models.CharField(blank=True, help_text='Position of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience_start_5',
            field=models.CharField(blank=True, help_text='give it a  start date.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='email',
            field=models.CharField(blank=True, help_text='Email of the User', max_length=80, null=True),
        ),
    ]
